apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
helmCharts:
  - name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes/
    releaseName: pihole
    namespace: pihole
    version: "2.35.0"
    valuesFile: values.yaml
